### ISSUE TITLE
Router bug: hitting browser back button 2 or more times fails to navigate

### ISSUE THREAD

**Issue by JudahGabriel** [thepassle/app-tools#12]
I've found a bug in the Router where if you navigate backwards two or more times, it'll never navigate to the previous page.

[Minimal repro here](https://app-tools-router-bug.glitch.me) (and [source here](https://glitch.com/edit/#!/app-tools-router-bug?path=public%2Findex.js%3A11%3A10)).

Repro steps:
1. Navigate to page A
2. Navigate to page B
3. Navigate to page C
4. Click browser back button (result: successfully navigates to page B)
5. Click browser back button (result: bug, it navigates to page B, which we're already on)

I don't yet know the source of the bug, but I'd be glad to submit a PR if you're willing to accept it.

**Comment by thepassle** [comment]
Im getting this on the repro: 
<img width="482" alt="image" src="https://user-images.githubusercontent.com/17054057/227644289-bcdd8ed1-bc23-4b46-8dd4-dfb783a1ba46.png">

**Comment by thepassle** [comment]
Ah I think its because onPopState we call navigate which then calls pushState 🤦‍♂️i can investigate some more tomorrow, or im happy to take a pr in the meantime

**Comment by JudahGabriel** [comment]
Thanks, I wondered if that is indeed the issue. Let me try preventing a pushState call on popState callback and see if that fixes it.

**Comment by JudahGabriel** [comment]
Yep, you're right. I updated the repro so that the code skips calling pushState when popState has been called. This fixes the issue.

I'll submit a PR momentarily.

**Comment by JudahGabriel** [comment]
OK! Opened [this PR](https://github.com/thepassle/app-tools/pull/13/files) which fixes the issue.
