### ISSUE TITLE
Router question: redirects with path params

### ISSUE THREAD

**Issue by JudahGabriel** [thepassle/app-tools#19]
I want this to work, but it doesn't:

```js
const router = new Router({
  routes: [
    {
      path: '/foo/:name',
      title: 'Foo',
    }
    {
      path: '/legacy/foo/:name',
      title: 'Foo',
      plugins: [
        redirect('/foo/:name'),
      ]
    }
  ]
});
```

If a user navigates to /legacy/foo/bar, I want it to redirect to /foo/bar.

Unfortunately it navigates to the literal URL `/foo/:name`

What's the best way to make this work? My thought is to create a plugin that finds the path params and inserts the real values for them. But that seems tedious because I'd have to write code to be aware of different kinds of path params, like `:name`, `:name?`, `:name+`, `:name(foo|bar)`, etc.

Is there a better way?

**Comment by thepassle** [comment]
We could accept a callback in addition to a string for the `redirect` plugin, and then pass the `context` to the callback, e.g.:

```js
redirect((context) => `/foo/${context.params.name}`);
```

and then change the implementation to something like:
```js
export function redirect(path) {
  return {
    name: 'redirect',
    shouldNavigate: (context) => ({
      condition: () => false,
      redirect: typeof path === 'function' ? path(context) : path
    })
  }
}
```

Would you be willing to create a PR for that? :)

**Comment by JudahGabriel** [comment]
Cool. Sure thing, I'll submit a PR.

**Comment by JudahGabriel** [comment]
[PR here](https://github.com/thepassle/app-tools/pull/20).

**Comment by JudahGabriel** [comment]
Thanks for merging! Closing this issue.
